### ISSUE TITLE
Script execution from untrusted input

### ISSUE THREAD

**Issue by hhyyrylainen** [StardustDL/RazorComponents.Markdown#75]
I'd like to use markdown with potentially untrusted user input. For that I was taking a look at potential XSS attacks from: https://portswigger.net/web-security/cross-site-scripting/cheat-sheet and to my surprise I found that this text when parsed as markdown causes an alert popup: `<svg><animate onbegin=alert(1) attributeName=x dur=1s>` meaning that XSS attack is possible through this library. Or do I need to configure the markdown pipeline to stop XSS (which would be nice to be the default option)?

**Comment by StardustDL** [comment]
Sounds important. This library use [Markdig](https://github.com/xoofx/markdig) as backend for markdown rendering, and it seems having no support for this scenario. I think we can add some post-steps to the rendering pipeline to stop XSS.
I found a JS library [js-xss](https://github.com/leizongmin/js-xss) may deal with this. I'm investigating how to integrate it into this library. Do you have better choices?

**Comment by hhyyrylainen** [comment]
I have not looked at XSS prevention besides the inbuilt text escaping in blazor (which isn't used with this markdown as this generates html directly), I would have to look into things more before I can recommend anything.

**Comment by hhyyrylainen** [comment]
Sorry for taking so long to test this, I had some higher priority things I needed to work on. Was this already released on nuget? I have `0.0.3.28` which doesn't seem to include the html sanitization...

**Comment by StardustDL** [comment]
> Sorry for taking so long to test this, I had some higher priority things I needed to work on. Was this already released on nuget? I have `0.0.3.28` which doesn't seem to include the html sanitization...

It doesn't matter. I'm glad to see you are testing this.

Yes, version `0.0.3.28` doesn't include the html sanitization. The recent commits which including html sanitization introduce some breaking changes in configuration so I want to release them in version `0.0.4.x`, which is not completed since there are some other things I need to do these days.

But there is a nightly build including html sanitization you can use for now. The NuGet feed source is https://sparkshine.pkgs.visualstudio.com/StardustDL/_packaging/feed/nuget/v3/index.json . It have StardustDL.RazorComponents.Markdown 0.0.3.29, the latest package built from the master branch.

BTW, html sanitization feature using the library [HtmlSanitize](https://github.com/mganss/HtmlSanitizer) is developing so maybe there are some bugs.

**Comment by hhyyrylainen** [comment]
Will the new version be uploaded to nuget at some point? It seems that `0.0.3.28` added 6 months ago is still the latest version on there.
